default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: GET

default_pruebas:
    path: /pruebas
    defaults: { _controller: "AppBundle:Default:pruebas" }
    methods: GET

default_pruebasJson:
    path: /pruebasJson
    defaults: { _controller: "AppBundle:Default:pruebasJson" }
    methods: POST

default_login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login" }
    methods: POST

default_checkToken:
    path: /checkToken
    defaults: { _controller: "AppBundle:Default:checkToken" }
    methods: POST